/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CobradasDialog.java
 *
 * Created on 30-ago-2009, 12:55:08
 */

package amltpvclient;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adam
 */
public class CobradasDialog extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    private static DefaultTableModel model;
    /** Creates new form CobradasDialog */
    public CobradasDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) cobradasTable.getModel();
        cobradasTable.getColumnModel().getColumn(2).setCellRenderer(new FormatRenderer());
        cobradasTable.getColumnModel().getColumn(0).setMaxWidth(80);
        cobradasTable.getColumnModel().getColumn(1).setMinWidth(100);
        cobradasTable.getColumnModel().getColumn(2).setMaxWidth(100);
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cobradasTable = new javax.swing.JTable();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(amltpvclient.AmltpvClientApp.class).getContext().getResourceMap(CobradasDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        cobradasTable.setFont(resourceMap.getFont("cobradasTable.font")); // NOI18N
        cobradasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesa", "Hora", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cobradasTable.setName("cobradasTable"); // NOI18N
        jScrollPane1.setViewportView(cobradasTable);
        cobradasTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("cobradasTable.columnModel.title0")); // NOI18N
        cobradasTable.getColumnModel().getColumn(1).setResizable(false);
        cobradasTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("cobradasTable.columnModel.title1")); // NOI18N
        cobradasTable.getColumnModel().getColumn(2).setResizable(false);
        cobradasTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("cobradasTable.columnModel.title2")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        this.setVisible(false);
    }//GEN-LAST:event_closeDialog

    public void addMesaCobrada(String mesa, String hora, String total){
        model.addRow(new Object[] {mesa,hora,total});
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cobradasTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
